- platform: lifx_cloud
  token: !secret lifx_cloud_token

- name: Cinema Normal
  entities:
    group.cinema_room_lights:
      state: on
      transition: 5
      brightness_pct: 85
      kelvin: 2500

- name: Cinema Movie
  entities:
    group.cinema_room_lights:
      state: on
      transition: 5
      brightness_pct: 10
      color_name: orange
